set(_CATKIN_CURRENT_PACKAGE "mpc_planner_dingo")
set(mpc_planner_dingo_VERSION "0.0.0")
set(mpc_planner_dingo_MAINTAINER "Oscar de Groot <o.m.degroot@tudelft.nl>")
set(mpc_planner_dingo_PACKAGE_FORMAT "3")
set(mpc_planner_dingo_BUILD_DEPENDS "roscpp" "mpc_planner" "mpc_planner_solver" "mpc_planner_util" "mpc_planner_types" "mpc_planner_msgs" "ros_tools" "dynamic_reconfigure" "nav_msgs")
set(mpc_planner_dingo_BUILD_EXPORT_DEPENDS "roscpp" "mpc_planner" "mpc_planner_solver" "mpc_planner_util" "mpc_planner_types" "mpc_planner_msgs" "ros_tools" "dynamic_reconfigure" "nav_msgs")
set(mpc_planner_dingo_BUILDTOOL_DEPENDS "catkin")
set(mpc_planner_dingo_BUILDTOOL_EXPORT_DEPENDS )
set(mpc_planner_dingo_EXEC_DEPENDS "dingo_simulator" "dingo_desktop" "dingo" "roadmap" "pedestrian_simulator" "roscpp" "mpc_planner" "mpc_planner_solver" "mpc_planner_util" "mpc_planner_types" "mpc_planner_msgs" "ros_tools" "dynamic_reconfigure" "nav_msgs")
set(mpc_planner_dingo_RUN_DEPENDS "dingo_simulator" "dingo_desktop" "dingo" "roadmap" "pedestrian_simulator" "roscpp" "mpc_planner" "mpc_planner_solver" "mpc_planner_util" "mpc_planner_types" "mpc_planner_msgs" "ros_tools" "dynamic_reconfigure" "nav_msgs")
set(mpc_planner_dingo_TEST_DEPENDS )
set(mpc_planner_dingo_DOC_DEPENDS )
set(mpc_planner_dingo_URL_WEBSITE "")
set(mpc_planner_dingo_URL_BUGTRACKER "")
set(mpc_planner_dingo_URL_REPOSITORY "")
set(mpc_planner_dingo_DEPRECATED "")