// Generated by gencpp from file mpc_planner_msgs/Gaussian.msg
// DO NOT EDIT!


#ifndef MPC_PLANNER_MSGS_MESSAGE_GAUSSIAN_H
#define MPC_PLANNER_MSGS_MESSAGE_GAUSSIAN_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <nav_msgs/Path.h>

namespace mpc_planner_msgs
{
template <class ContainerAllocator>
struct Gaussian_
{
  typedef Gaussian_<ContainerAllocator> Type;

  Gaussian_()
    : mean()
    , major_semiaxis()
    , minor_semiaxis()  {
    }
  Gaussian_(const ContainerAllocator& _alloc)
    : mean(_alloc)
    , major_semiaxis(_alloc)
    , minor_semiaxis(_alloc)  {
  (void)_alloc;
    }



   typedef  ::nav_msgs::Path_<ContainerAllocator>  _mean_type;
  _mean_type mean;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _major_semiaxis_type;
  _major_semiaxis_type major_semiaxis;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _minor_semiaxis_type;
  _minor_semiaxis_type minor_semiaxis;





  typedef boost::shared_ptr< ::mpc_planner_msgs::Gaussian_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mpc_planner_msgs::Gaussian_<ContainerAllocator> const> ConstPtr;

}; // struct Gaussian_

typedef ::mpc_planner_msgs::Gaussian_<std::allocator<void> > Gaussian;

typedef boost::shared_ptr< ::mpc_planner_msgs::Gaussian > GaussianPtr;
typedef boost::shared_ptr< ::mpc_planner_msgs::Gaussian const> GaussianConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mpc_planner_msgs::Gaussian_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mpc_planner_msgs::Gaussian_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mpc_planner_msgs::Gaussian_<ContainerAllocator1> & lhs, const ::mpc_planner_msgs::Gaussian_<ContainerAllocator2> & rhs)
{
  return lhs.mean == rhs.mean &&
    lhs.major_semiaxis == rhs.major_semiaxis &&
    lhs.minor_semiaxis == rhs.minor_semiaxis;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mpc_planner_msgs::Gaussian_<ContainerAllocator1> & lhs, const ::mpc_planner_msgs::Gaussian_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mpc_planner_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mpc_planner_msgs::Gaussian_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mpc_planner_msgs::Gaussian_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mpc_planner_msgs::Gaussian_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mpc_planner_msgs::Gaussian_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mpc_planner_msgs::Gaussian_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mpc_planner_msgs::Gaussian_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mpc_planner_msgs::Gaussian_<ContainerAllocator> >
{
  static const char* value()
  {
    return "850460d51db9d70a66e94a860b9ab01d";
  }

  static const char* value(const ::mpc_planner_msgs::Gaussian_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x850460d51db9d70aULL;
  static const uint64_t static_value2 = 0x66e94a860b9ab01dULL;
};

template<class ContainerAllocator>
struct DataType< ::mpc_planner_msgs::Gaussian_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mpc_planner_msgs/Gaussian";
  }

  static const char* value(const ::mpc_planner_msgs::Gaussian_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mpc_planner_msgs::Gaussian_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Trajectory of the mean prediction\n"
"nav_msgs/Path mean\n"
"\n"
"# Covariances decomposed into their major and minor axes\n"
"float64[] major_semiaxis\n"
"float64[] minor_semiaxis\n"
"================================================================================\n"
"MSG: nav_msgs/Path\n"
"#An array of poses that represents a Path for a robot to follow\n"
"Header header\n"
"geometry_msgs/PoseStamped[] poses\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::mpc_planner_msgs::Gaussian_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mpc_planner_msgs::Gaussian_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mean);
      stream.next(m.major_semiaxis);
      stream.next(m.minor_semiaxis);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Gaussian_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mpc_planner_msgs::Gaussian_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mpc_planner_msgs::Gaussian_<ContainerAllocator>& v)
  {
    s << indent << "mean: ";
    s << std::endl;
    Printer< ::nav_msgs::Path_<ContainerAllocator> >::stream(s, indent + "  ", v.mean);
    s << indent << "major_semiaxis[]" << std::endl;
    for (size_t i = 0; i < v.major_semiaxis.size(); ++i)
    {
      s << indent << "  major_semiaxis[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.major_semiaxis[i]);
    }
    s << indent << "minor_semiaxis[]" << std::endl;
    for (size_t i = 0; i < v.minor_semiaxis.size(); ++i)
    {
      s << indent << "  minor_semiaxis[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.minor_semiaxis[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MPC_PLANNER_MSGS_MESSAGE_GAUSSIAN_H
