// Generated by gencpp from file mpc_planner_msgs/ObstacleGMM.msg
// DO NOT EDIT!


#ifndef MPC_PLANNER_MSGS_MESSAGE_OBSTACLEGMM_H
#define MPC_PLANNER_MSGS_MESSAGE_OBSTACLEGMM_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>
#include <mpc_planner_msgs/Gaussian.h>

namespace mpc_planner_msgs
{
template <class ContainerAllocator>
struct ObstacleGMM_
{
  typedef ObstacleGMM_<ContainerAllocator> Type;

  ObstacleGMM_()
    : id(0)
    , pose()
    , gaussians()
    , probabilities()  {
    }
  ObstacleGMM_(const ContainerAllocator& _alloc)
    : id(0)
    , pose(_alloc)
    , gaussians(_alloc)
    , probabilities(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef std::vector< ::mpc_planner_msgs::Gaussian_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::mpc_planner_msgs::Gaussian_<ContainerAllocator> >> _gaussians_type;
  _gaussians_type gaussians;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _probabilities_type;
  _probabilities_type probabilities;





  typedef boost::shared_ptr< ::mpc_planner_msgs::ObstacleGMM_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mpc_planner_msgs::ObstacleGMM_<ContainerAllocator> const> ConstPtr;

}; // struct ObstacleGMM_

typedef ::mpc_planner_msgs::ObstacleGMM_<std::allocator<void> > ObstacleGMM;

typedef boost::shared_ptr< ::mpc_planner_msgs::ObstacleGMM > ObstacleGMMPtr;
typedef boost::shared_ptr< ::mpc_planner_msgs::ObstacleGMM const> ObstacleGMMConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mpc_planner_msgs::ObstacleGMM_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mpc_planner_msgs::ObstacleGMM_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mpc_planner_msgs::ObstacleGMM_<ContainerAllocator1> & lhs, const ::mpc_planner_msgs::ObstacleGMM_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.pose == rhs.pose &&
    lhs.gaussians == rhs.gaussians &&
    lhs.probabilities == rhs.probabilities;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mpc_planner_msgs::ObstacleGMM_<ContainerAllocator1> & lhs, const ::mpc_planner_msgs::ObstacleGMM_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mpc_planner_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mpc_planner_msgs::ObstacleGMM_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mpc_planner_msgs::ObstacleGMM_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mpc_planner_msgs::ObstacleGMM_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mpc_planner_msgs::ObstacleGMM_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mpc_planner_msgs::ObstacleGMM_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mpc_planner_msgs::ObstacleGMM_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mpc_planner_msgs::ObstacleGMM_<ContainerAllocator> >
{
  static const char* value()
  {
    return "43fafe3d1d2bd26d6dea45245b7944b1";
  }

  static const char* value(const ::mpc_planner_msgs::ObstacleGMM_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x43fafe3d1d2bd26dULL;
  static const uint64_t static_value2 = 0x6dea45245b7944b1ULL;
};

template<class ContainerAllocator>
struct DataType< ::mpc_planner_msgs::ObstacleGMM_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mpc_planner_msgs/ObstacleGMM";
  }

  static const char* value(const ::mpc_planner_msgs::ObstacleGMM_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mpc_planner_msgs::ObstacleGMM_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ID for obstacle association\n"
"int32 id\n"
"\n"
"# Current pose of the obstacle\n"
"geometry_msgs/Pose pose\n"
"\n"
"# List of Gaussians and their probabilities\n"
"mpc_planner_msgs/Gaussian[] gaussians\n"
"float64[] probabilities\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: mpc_planner_msgs/Gaussian\n"
"# Trajectory of the mean prediction\n"
"nav_msgs/Path mean\n"
"\n"
"# Covariances decomposed into their major and minor axes\n"
"float64[] major_semiaxis\n"
"float64[] minor_semiaxis\n"
"================================================================================\n"
"MSG: nav_msgs/Path\n"
"#An array of poses that represents a Path for a robot to follow\n"
"Header header\n"
"geometry_msgs/PoseStamped[] poses\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
;
  }

  static const char* value(const ::mpc_planner_msgs::ObstacleGMM_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mpc_planner_msgs::ObstacleGMM_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.pose);
      stream.next(m.gaussians);
      stream.next(m.probabilities);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObstacleGMM_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mpc_planner_msgs::ObstacleGMM_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mpc_planner_msgs::ObstacleGMM_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "gaussians[]" << std::endl;
    for (size_t i = 0; i < v.gaussians.size(); ++i)
    {
      s << indent << "  gaussians[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::mpc_planner_msgs::Gaussian_<ContainerAllocator> >::stream(s, indent + "    ", v.gaussians[i]);
    }
    s << indent << "probabilities[]" << std::endl;
    for (size_t i = 0; i < v.probabilities.size(); ++i)
    {
      s << indent << "  probabilities[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.probabilities[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MPC_PLANNER_MSGS_MESSAGE_OBSTACLEGMM_H
