#!/usr/bin/env sh
# generated from catkin/python/catkin/environment_cache.py

# based on a snapshot of the environment before and after calling the setup script
# it emulates the modifications of the setup script without recurring computations

# new environment variables

# modified environment variables
export CMAKE_PREFIX_PATH="/home/soon/workspace/devel_isolated/guidance_planner:$CMAKE_PREFIX_PATH"
export LD_LIBRARY_PATH='/home/soon/workspace/devel_isolated/guidance_planner/lib:/home/soon/workspace/devel_isolated/decomp_util/lib:/home/soon/workspace/devel_isolated/ros_tools/lib:/home/soon/workspace/devel_isolated/roadmap_msgs/lib:/home/soon/workspace/devel_isolated/pedsim_original/lib:/home/soon/workspace/devel_isolated/mpc_planner_types/lib:/home/soon/workspace/devel_isolated/mpc_planner_msgs/lib:/home/soon/workspace/devel_isolated/mobile_robot_state_publisher/lib:/home/soon/workspace/devel_isolated/jackal_tutorials/lib:/home/soon/workspace/devel_isolated/jackal_navigation/lib:/home/soon/workspace/devel_isolated/jackal_msgs/lib:/home/soon/workspace/devel_isolated/jackal_gazebo/lib:/home/soon/workspace/devel_isolated/jackal_description/lib:/home/soon/workspace/devel_isolated/jackal_control/lib:/home/soon/workspace/devel_isolated/asr_rapidxml/lib:/home/soon/mpc_ws/devel_isolated/decomp_test_node/lib:/home/soon/mpc_ws/devel_isolated/decomp_ros_utils/lib:/home/soon/mpc_ws/devel_isolated/decomp_ros_msgs/lib:/home/soon/mpc_ws/devel_isolated/catkin_simple/lib:/home/soon/mpc_ws/devel/lib:/home/soon/turtle_ws/devel/lib:/home/soon/catkin_ws/devel/lib:/opt/ros/noetic/lib:/opt/ros/noetic/lib/x86_64-linux-gnu:~/acados/lib:~/acados/lib:~/acados/lib:~/acados/lib:~/workspace/acados/lib:~/workspace/acados/lib'
export PATH='/opt/ros/noetic/bin:/home/soon/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
export PKG_CONFIG_PATH='/home/soon/workspace/devel_isolated/guidance_planner/lib/pkgconfig:/home/soon/workspace/devel_isolated/decomp_util/lib/pkgconfig:/home/soon/workspace/devel_isolated/ros_tools/lib/pkgconfig:/home/soon/workspace/devel_isolated/roadmap_msgs/lib/pkgconfig:/home/soon/workspace/devel_isolated/pedsim_original/lib/pkgconfig:/home/soon/workspace/devel_isolated/mpc_planner_types/lib/pkgconfig:/home/soon/workspace/devel_isolated/mpc_planner_msgs/lib/pkgconfig:/home/soon/workspace/devel_isolated/mobile_robot_state_publisher/lib/pkgconfig:/home/soon/workspace/devel_isolated/jackal_tutorials/lib/pkgconfig:/home/soon/workspace/devel_isolated/jackal_navigation/lib/pkgconfig:/home/soon/workspace/devel_isolated/jackal_msgs/lib/pkgconfig:/home/soon/workspace/devel_isolated/jackal_gazebo/lib/pkgconfig:/home/soon/workspace/devel_isolated/jackal_description/lib/pkgconfig:/home/soon/workspace/devel_isolated/jackal_control/lib/pkgconfig:/home/soon/workspace/devel_isolated/asr_rapidxml/lib/pkgconfig:/home/soon/mpc_ws/devel_isolated/decomp_test_node/lib/pkgconfig:/home/soon/mpc_ws/devel_isolated/decomp_ros_utils/lib/pkgconfig:/home/soon/mpc_ws/devel_isolated/decomp_ros_msgs/lib/pkgconfig:/home/soon/mpc_ws/devel_isolated/catkin_simple/lib/pkgconfig:/home/soon/mpc_ws/devel/lib/pkgconfig:/home/soon/turtle_ws/devel/lib/pkgconfig:/home/soon/catkin_ws/devel/lib/pkgconfig:/opt/ros/noetic/lib/pkgconfig:/opt/ros/noetic/lib/x86_64-linux-gnu/pkgconfig'
export PYTHONPATH='/home/soon/workspace/devel_isolated/guidance_planner/lib/python3/dist-packages:/home/soon/workspace/devel_isolated/roadmap_msgs/lib/python3/dist-packages:/home/soon/workspace/devel_isolated/mpc_planner_msgs/lib/python3/dist-packages:/home/soon/workspace/devel_isolated/jackal_msgs/lib/python3/dist-packages:/home/soon/mpc_ws/devel_isolated/decomp_ros_msgs/lib/python3/dist-packages:/home/soon/turtle_ws/devel/lib/python3/dist-packages:/home/soon/catkin_ws/devel/lib/python3/dist-packages:/opt/ros/noetic/lib/python3/dist-packages'
export ROSLISP_PACKAGE_DIRECTORIES="/home/soon/workspace/devel_isolated/guidance_planner/share/common-lisp:$ROSLISP_PACKAGE_DIRECTORIES"
export ROS_PACKAGE_PATH="/home/soon/workspace/src/guidance_planner:/home/soon/workspace/devel_isolated/decomp_util/share:$ROS_PACKAGE_PATH"