set(_CATKIN_CURRENT_PACKAGE "mpc_planner_rosnavigation")
set(mpc_planner_rosnavigation_VERSION "0.0.0")
set(mpc_planner_rosnavigation_MAINTAINER "Oscar de Groot <o.m.degroot@tudelft.nl>")
set(mpc_planner_rosnavigation_PACKAGE_FORMAT "3")
set(mpc_planner_rosnavigation_BUILD_DEPENDS "roscpp" "mpc_planner" "mpc_planner_msgs" "mpc_planner_modules" "mpc_planner_solver" "mpc_planner_util" "mpc_planner_types" "ros_tools" "dynamic_reconfigure" "tf2_ros" "tf2_geometry_msgs" "nav_core" "base_local_planner" "costmap_2d" "costmap_converter" "nav_msgs" "geometry_msgs" "angles" "pluginlib" "navfn" "guidance_planner")
set(mpc_planner_rosnavigation_BUILD_EXPORT_DEPENDS "roscpp" "mpc_planner" "mpc_planner_msgs" "mpc_planner_modules" "mpc_planner_solver" "mpc_planner_util" "mpc_planner_types" "ros_tools" "dynamic_reconfigure" "tf2_ros" "tf2_geometry_msgs" "nav_core" "base_local_planner" "costmap_2d" "costmap_converter" "nav_msgs" "geometry_msgs" "angles" "pluginlib" "navfn" "guidance_planner")
set(mpc_planner_rosnavigation_BUILDTOOL_DEPENDS "catkin")
set(mpc_planner_rosnavigation_BUILDTOOL_EXPORT_DEPENDS )
set(mpc_planner_rosnavigation_EXEC_DEPENDS "pedestrian_simulator" "jackal_gazebo" "jackal_navigation" "mobile_robot_state_publisher" "roadmap" "roscpp" "mpc_planner" "mpc_planner_msgs" "mpc_planner_modules" "mpc_planner_solver" "mpc_planner_util" "mpc_planner_types" "ros_tools" "dynamic_reconfigure" "tf2_ros" "tf2_geometry_msgs" "nav_core" "base_local_planner" "costmap_2d" "costmap_converter" "nav_msgs" "geometry_msgs" "angles" "pluginlib" "navfn" "guidance_planner")
set(mpc_planner_rosnavigation_RUN_DEPENDS "pedestrian_simulator" "jackal_gazebo" "jackal_navigation" "mobile_robot_state_publisher" "roadmap" "roscpp" "mpc_planner" "mpc_planner_msgs" "mpc_planner_modules" "mpc_planner_solver" "mpc_planner_util" "mpc_planner_types" "ros_tools" "dynamic_reconfigure" "tf2_ros" "tf2_geometry_msgs" "nav_core" "base_local_planner" "costmap_2d" "costmap_converter" "nav_msgs" "geometry_msgs" "angles" "pluginlib" "navfn" "guidance_planner")
set(mpc_planner_rosnavigation_TEST_DEPENDS )
set(mpc_planner_rosnavigation_DOC_DEPENDS )
set(mpc_planner_rosnavigation_URL_WEBSITE "")
set(mpc_planner_rosnavigation_URL_BUGTRACKER "")
set(mpc_planner_rosnavigation_URL_REPOSITORY "")
set(mpc_planner_rosnavigation_DEPRECATED "")