//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the mpc_planner_jackalsimulator package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __mpc_planner_jackalsimulator__JACKALSIMULATORCONFIG_H__
#define __mpc_planner_jackalsimulator__JACKALSIMULATORCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace mpc_planner_jackalsimulator
{
  class jackalsimulatorConfigStatics;

  class jackalsimulatorConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(jackalsimulatorConfig &config, const jackalsimulatorConfig &max, const jackalsimulatorConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const jackalsimulatorConfig &config1, const jackalsimulatorConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, jackalsimulatorConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const jackalsimulatorConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, jackalsimulatorConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const jackalsimulatorConfig &config) const = 0;
      virtual void getValue(const jackalsimulatorConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T jackalsimulatorConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T jackalsimulatorConfig::* field;

      virtual void clamp(jackalsimulatorConfig &config, const jackalsimulatorConfig &max, const jackalsimulatorConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const jackalsimulatorConfig &config1, const jackalsimulatorConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, jackalsimulatorConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const jackalsimulatorConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, jackalsimulatorConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const jackalsimulatorConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const jackalsimulatorConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, jackalsimulatorConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, jackalsimulatorConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<jackalsimulatorConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(jackalsimulatorConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);


      }
    }

    

    bool state;
    std::string name;

    class WEIGHTS
{
  public:
    WEIGHTS()
    {
      state = true;
      name = "Weights";
    }

    void setParams(jackalsimulatorConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("acceleration"==(*_i)->name){acceleration = boost::any_cast<double>(val);}
        if("angular_velocity"==(*_i)->name){angular_velocity = boost::any_cast<double>(val);}
        if("velocity"==(*_i)->name){velocity = boost::any_cast<double>(val);}
        if("reference_velocity"==(*_i)->name){reference_velocity = boost::any_cast<double>(val);}
        if("contour"==(*_i)->name){contour = boost::any_cast<double>(val);}
        if("lag"==(*_i)->name){lag = boost::any_cast<double>(val);}
        if("terminal_angle"==(*_i)->name){terminal_angle = boost::any_cast<double>(val);}
        if("terminal_contouring"==(*_i)->name){terminal_contouring = boost::any_cast<double>(val);}
      }
    }

    double acceleration;
double angular_velocity;
double velocity;
double reference_velocity;
double contour;
double lag;
double terminal_angle;
double terminal_contouring;

    bool state;
    std::string name;

    
}weights;

}groups;



//#line 7 "/home/soon/workspace/src/mpc_planner/mpc_planner_jackalsimulator/cfg/jackalsimulator.cfg"
      double acceleration;
//#line 8 "/home/soon/workspace/src/mpc_planner/mpc_planner_jackalsimulator/cfg/jackalsimulator.cfg"
      double angular_velocity;
//#line 9 "/home/soon/workspace/src/mpc_planner/mpc_planner_jackalsimulator/cfg/jackalsimulator.cfg"
      double velocity;
//#line 10 "/home/soon/workspace/src/mpc_planner/mpc_planner_jackalsimulator/cfg/jackalsimulator.cfg"
      double reference_velocity;
//#line 11 "/home/soon/workspace/src/mpc_planner/mpc_planner_jackalsimulator/cfg/jackalsimulator.cfg"
      double contour;
//#line 12 "/home/soon/workspace/src/mpc_planner/mpc_planner_jackalsimulator/cfg/jackalsimulator.cfg"
      double lag;
//#line 13 "/home/soon/workspace/src/mpc_planner/mpc_planner_jackalsimulator/cfg/jackalsimulator.cfg"
      double terminal_angle;
//#line 14 "/home/soon/workspace/src/mpc_planner/mpc_planner_jackalsimulator/cfg/jackalsimulator.cfg"
      double terminal_contouring;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("jackalsimulatorConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const jackalsimulatorConfig &__max__ = __getMax__();
      const jackalsimulatorConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const jackalsimulatorConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const jackalsimulatorConfig &__getDefault__();
    static const jackalsimulatorConfig &__getMax__();
    static const jackalsimulatorConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const jackalsimulatorConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void jackalsimulatorConfig::ParamDescription<std::string>::clamp(jackalsimulatorConfig &config, const jackalsimulatorConfig &max, const jackalsimulatorConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class jackalsimulatorConfigStatics
  {
    friend class jackalsimulatorConfig;

    jackalsimulatorConfigStatics()
    {
jackalsimulatorConfig::GroupDescription<jackalsimulatorConfig::DEFAULT, jackalsimulatorConfig> Default("Default", "", 0, 0, true, &jackalsimulatorConfig::groups);
jackalsimulatorConfig::GroupDescription<jackalsimulatorConfig::DEFAULT::WEIGHTS, jackalsimulatorConfig::DEFAULT> Weights("Weights", "Weights", 0, 1, true, &jackalsimulatorConfig::DEFAULT::weights);
//#line 7 "/home/soon/workspace/src/mpc_planner/mpc_planner_jackalsimulator/cfg/jackalsimulator.cfg"
      __min__.acceleration = 0.0;
//#line 7 "/home/soon/workspace/src/mpc_planner/mpc_planner_jackalsimulator/cfg/jackalsimulator.cfg"
      __max__.acceleration = 100.0;
//#line 7 "/home/soon/workspace/src/mpc_planner/mpc_planner_jackalsimulator/cfg/jackalsimulator.cfg"
      __default__.acceleration = 1.0;
//#line 7 "/home/soon/workspace/src/mpc_planner/mpc_planner_jackalsimulator/cfg/jackalsimulator.cfg"
      Weights.abstract_parameters.push_back(jackalsimulatorConfig::AbstractParamDescriptionConstPtr(new jackalsimulatorConfig::ParamDescription<double>("acceleration", "double", 1, "acceleration", "", &jackalsimulatorConfig::acceleration)));
//#line 7 "/home/soon/workspace/src/mpc_planner/mpc_planner_jackalsimulator/cfg/jackalsimulator.cfg"
      __param_descriptions__.push_back(jackalsimulatorConfig::AbstractParamDescriptionConstPtr(new jackalsimulatorConfig::ParamDescription<double>("acceleration", "double", 1, "acceleration", "", &jackalsimulatorConfig::acceleration)));
//#line 8 "/home/soon/workspace/src/mpc_planner/mpc_planner_jackalsimulator/cfg/jackalsimulator.cfg"
      __min__.angular_velocity = 0.0;
//#line 8 "/home/soon/workspace/src/mpc_planner/mpc_planner_jackalsimulator/cfg/jackalsimulator.cfg"
      __max__.angular_velocity = 100.0;
//#line 8 "/home/soon/workspace/src/mpc_planner/mpc_planner_jackalsimulator/cfg/jackalsimulator.cfg"
      __default__.angular_velocity = 1.0;
//#line 8 "/home/soon/workspace/src/mpc_planner/mpc_planner_jackalsimulator/cfg/jackalsimulator.cfg"
      Weights.abstract_parameters.push_back(jackalsimulatorConfig::AbstractParamDescriptionConstPtr(new jackalsimulatorConfig::ParamDescription<double>("angular_velocity", "double", 1, "angular_velocity", "", &jackalsimulatorConfig::angular_velocity)));
//#line 8 "/home/soon/workspace/src/mpc_planner/mpc_planner_jackalsimulator/cfg/jackalsimulator.cfg"
      __param_descriptions__.push_back(jackalsimulatorConfig::AbstractParamDescriptionConstPtr(new jackalsimulatorConfig::ParamDescription<double>("angular_velocity", "double", 1, "angular_velocity", "", &jackalsimulatorConfig::angular_velocity)));
//#line 9 "/home/soon/workspace/src/mpc_planner/mpc_planner_jackalsimulator/cfg/jackalsimulator.cfg"
      __min__.velocity = 0.0;
//#line 9 "/home/soon/workspace/src/mpc_planner/mpc_planner_jackalsimulator/cfg/jackalsimulator.cfg"
      __max__.velocity = 100.0;
//#line 9 "/home/soon/workspace/src/mpc_planner/mpc_planner_jackalsimulator/cfg/jackalsimulator.cfg"
      __default__.velocity = 1.0;
//#line 9 "/home/soon/workspace/src/mpc_planner/mpc_planner_jackalsimulator/cfg/jackalsimulator.cfg"
      Weights.abstract_parameters.push_back(jackalsimulatorConfig::AbstractParamDescriptionConstPtr(new jackalsimulatorConfig::ParamDescription<double>("velocity", "double", 1, "velocity", "", &jackalsimulatorConfig::velocity)));
//#line 9 "/home/soon/workspace/src/mpc_planner/mpc_planner_jackalsimulator/cfg/jackalsimulator.cfg"
      __param_descriptions__.push_back(jackalsimulatorConfig::AbstractParamDescriptionConstPtr(new jackalsimulatorConfig::ParamDescription<double>("velocity", "double", 1, "velocity", "", &jackalsimulatorConfig::velocity)));
//#line 10 "/home/soon/workspace/src/mpc_planner/mpc_planner_jackalsimulator/cfg/jackalsimulator.cfg"
      __min__.reference_velocity = 0.0;
//#line 10 "/home/soon/workspace/src/mpc_planner/mpc_planner_jackalsimulator/cfg/jackalsimulator.cfg"
      __max__.reference_velocity = 100.0;
//#line 10 "/home/soon/workspace/src/mpc_planner/mpc_planner_jackalsimulator/cfg/jackalsimulator.cfg"
      __default__.reference_velocity = 1.0;
//#line 10 "/home/soon/workspace/src/mpc_planner/mpc_planner_jackalsimulator/cfg/jackalsimulator.cfg"
      Weights.abstract_parameters.push_back(jackalsimulatorConfig::AbstractParamDescriptionConstPtr(new jackalsimulatorConfig::ParamDescription<double>("reference_velocity", "double", 1, "reference_velocity", "", &jackalsimulatorConfig::reference_velocity)));
//#line 10 "/home/soon/workspace/src/mpc_planner/mpc_planner_jackalsimulator/cfg/jackalsimulator.cfg"
      __param_descriptions__.push_back(jackalsimulatorConfig::AbstractParamDescriptionConstPtr(new jackalsimulatorConfig::ParamDescription<double>("reference_velocity", "double", 1, "reference_velocity", "", &jackalsimulatorConfig::reference_velocity)));
//#line 11 "/home/soon/workspace/src/mpc_planner/mpc_planner_jackalsimulator/cfg/jackalsimulator.cfg"
      __min__.contour = 0.0;
//#line 11 "/home/soon/workspace/src/mpc_planner/mpc_planner_jackalsimulator/cfg/jackalsimulator.cfg"
      __max__.contour = 100.0;
//#line 11 "/home/soon/workspace/src/mpc_planner/mpc_planner_jackalsimulator/cfg/jackalsimulator.cfg"
      __default__.contour = 1.0;
//#line 11 "/home/soon/workspace/src/mpc_planner/mpc_planner_jackalsimulator/cfg/jackalsimulator.cfg"
      Weights.abstract_parameters.push_back(jackalsimulatorConfig::AbstractParamDescriptionConstPtr(new jackalsimulatorConfig::ParamDescription<double>("contour", "double", 1, "contour", "", &jackalsimulatorConfig::contour)));
//#line 11 "/home/soon/workspace/src/mpc_planner/mpc_planner_jackalsimulator/cfg/jackalsimulator.cfg"
      __param_descriptions__.push_back(jackalsimulatorConfig::AbstractParamDescriptionConstPtr(new jackalsimulatorConfig::ParamDescription<double>("contour", "double", 1, "contour", "", &jackalsimulatorConfig::contour)));
//#line 12 "/home/soon/workspace/src/mpc_planner/mpc_planner_jackalsimulator/cfg/jackalsimulator.cfg"
      __min__.lag = 0.0;
//#line 12 "/home/soon/workspace/src/mpc_planner/mpc_planner_jackalsimulator/cfg/jackalsimulator.cfg"
      __max__.lag = 100.0;
//#line 12 "/home/soon/workspace/src/mpc_planner/mpc_planner_jackalsimulator/cfg/jackalsimulator.cfg"
      __default__.lag = 1.0;
//#line 12 "/home/soon/workspace/src/mpc_planner/mpc_planner_jackalsimulator/cfg/jackalsimulator.cfg"
      Weights.abstract_parameters.push_back(jackalsimulatorConfig::AbstractParamDescriptionConstPtr(new jackalsimulatorConfig::ParamDescription<double>("lag", "double", 1, "lag", "", &jackalsimulatorConfig::lag)));
//#line 12 "/home/soon/workspace/src/mpc_planner/mpc_planner_jackalsimulator/cfg/jackalsimulator.cfg"
      __param_descriptions__.push_back(jackalsimulatorConfig::AbstractParamDescriptionConstPtr(new jackalsimulatorConfig::ParamDescription<double>("lag", "double", 1, "lag", "", &jackalsimulatorConfig::lag)));
//#line 13 "/home/soon/workspace/src/mpc_planner/mpc_planner_jackalsimulator/cfg/jackalsimulator.cfg"
      __min__.terminal_angle = 0.0;
//#line 13 "/home/soon/workspace/src/mpc_planner/mpc_planner_jackalsimulator/cfg/jackalsimulator.cfg"
      __max__.terminal_angle = 100.0;
//#line 13 "/home/soon/workspace/src/mpc_planner/mpc_planner_jackalsimulator/cfg/jackalsimulator.cfg"
      __default__.terminal_angle = 1.0;
//#line 13 "/home/soon/workspace/src/mpc_planner/mpc_planner_jackalsimulator/cfg/jackalsimulator.cfg"
      Weights.abstract_parameters.push_back(jackalsimulatorConfig::AbstractParamDescriptionConstPtr(new jackalsimulatorConfig::ParamDescription<double>("terminal_angle", "double", 1, "terminal_angle", "", &jackalsimulatorConfig::terminal_angle)));
//#line 13 "/home/soon/workspace/src/mpc_planner/mpc_planner_jackalsimulator/cfg/jackalsimulator.cfg"
      __param_descriptions__.push_back(jackalsimulatorConfig::AbstractParamDescriptionConstPtr(new jackalsimulatorConfig::ParamDescription<double>("terminal_angle", "double", 1, "terminal_angle", "", &jackalsimulatorConfig::terminal_angle)));
//#line 14 "/home/soon/workspace/src/mpc_planner/mpc_planner_jackalsimulator/cfg/jackalsimulator.cfg"
      __min__.terminal_contouring = 0.0;
//#line 14 "/home/soon/workspace/src/mpc_planner/mpc_planner_jackalsimulator/cfg/jackalsimulator.cfg"
      __max__.terminal_contouring = 100.0;
//#line 14 "/home/soon/workspace/src/mpc_planner/mpc_planner_jackalsimulator/cfg/jackalsimulator.cfg"
      __default__.terminal_contouring = 1.0;
//#line 14 "/home/soon/workspace/src/mpc_planner/mpc_planner_jackalsimulator/cfg/jackalsimulator.cfg"
      Weights.abstract_parameters.push_back(jackalsimulatorConfig::AbstractParamDescriptionConstPtr(new jackalsimulatorConfig::ParamDescription<double>("terminal_contouring", "double", 1, "terminal_contouring", "", &jackalsimulatorConfig::terminal_contouring)));
//#line 14 "/home/soon/workspace/src/mpc_planner/mpc_planner_jackalsimulator/cfg/jackalsimulator.cfg"
      __param_descriptions__.push_back(jackalsimulatorConfig::AbstractParamDescriptionConstPtr(new jackalsimulatorConfig::ParamDescription<double>("terminal_contouring", "double", 1, "terminal_contouring", "", &jackalsimulatorConfig::terminal_contouring)));
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Weights.convertParams();
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(jackalsimulatorConfig::AbstractGroupDescriptionConstPtr(new jackalsimulatorConfig::GroupDescription<jackalsimulatorConfig::DEFAULT::WEIGHTS, jackalsimulatorConfig::DEFAULT>(Weights)));
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(jackalsimulatorConfig::AbstractGroupDescriptionConstPtr(new jackalsimulatorConfig::GroupDescription<jackalsimulatorConfig::DEFAULT::WEIGHTS, jackalsimulatorConfig::DEFAULT>(Weights)));
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(jackalsimulatorConfig::AbstractGroupDescriptionConstPtr(new jackalsimulatorConfig::GroupDescription<jackalsimulatorConfig::DEFAULT, jackalsimulatorConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<jackalsimulatorConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<jackalsimulatorConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<jackalsimulatorConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    jackalsimulatorConfig __max__;
    jackalsimulatorConfig __min__;
    jackalsimulatorConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const jackalsimulatorConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static jackalsimulatorConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &jackalsimulatorConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const jackalsimulatorConfig &jackalsimulatorConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const jackalsimulatorConfig &jackalsimulatorConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const jackalsimulatorConfig &jackalsimulatorConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<jackalsimulatorConfig::AbstractParamDescriptionConstPtr> &jackalsimulatorConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<jackalsimulatorConfig::AbstractGroupDescriptionConstPtr> &jackalsimulatorConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const jackalsimulatorConfigStatics *jackalsimulatorConfig::__get_statics__()
  {
    const static jackalsimulatorConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = jackalsimulatorConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __JACKALSIMULATORRECONFIGURATOR_H__
