set(_CATKIN_CURRENT_PACKAGE "decomp_util")
set(decomp_util_VERSION "1.0.0")
set(decomp_util_MAINTAINER "sikang <sikang@seas.upenn.edu>")
set(decomp_util_PACKAGE_FORMAT "2")
set(decomp_util_BUILD_DEPENDS "ros_tools")
set(decomp_util_BUILD_EXPORT_DEPENDS "ros_tools")
set(decomp_util_BUILDTOOL_DEPENDS "catkin")
set(decomp_util_BUILDTOOL_EXPORT_DEPENDS )
set(decomp_util_EXEC_DEPENDS "ros_tools")
set(decomp_util_RUN_DEPENDS "ros_tools")
set(decomp_util_TEST_DEPENDS )
set(decomp_util_DOC_DEPENDS )
set(decomp_util_URL_WEBSITE "")
set(decomp_util_URL_BUGTRACKER "")
set(decomp_util_URL_REPOSITORY "")
set(decomp_util_DEPRECATED "")