set(_CATKIN_CURRENT_PACKAGE "pedestrian_simulator")
set(pedestrian_simulator_VERSION "0.0.0")
set(pedestrian_simulator_MAINTAINER "Oscar de Groot <o.m.degroot@tudelft.nl>")
set(pedestrian_simulator_PACKAGE_FORMAT "2")
set(pedestrian_simulator_BUILD_DEPENDS "roscpp" "std_msgs" "geometry_msgs" "asr_rapidxml" "roslib" "ros_tools" "pedsim_original" "mpc_planner_msgs" "std_srvs" "message_filters" "derived_object_msgs" "sensor_msgs")
set(pedestrian_simulator_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs" "geometry_msgs" "asr_rapidxml" "roslib" "ros_tools" "pedsim_original" "mpc_planner_msgs" "std_srvs" "message_filters" "derived_object_msgs" "sensor_msgs")
set(pedestrian_simulator_BUILDTOOL_DEPENDS "catkin")
set(pedestrian_simulator_BUILDTOOL_EXPORT_DEPENDS )
set(pedestrian_simulator_EXEC_DEPENDS "roscpp" "std_msgs" "geometry_msgs" "asr_rapidxml" "roslib" "ros_tools" "pedsim_original" "mpc_planner_msgs" "std_srvs" "message_filters" "derived_object_msgs" "sensor_msgs")
set(pedestrian_simulator_RUN_DEPENDS "roscpp" "std_msgs" "geometry_msgs" "asr_rapidxml" "roslib" "ros_tools" "pedsim_original" "mpc_planner_msgs" "std_srvs" "message_filters" "derived_object_msgs" "sensor_msgs")
set(pedestrian_simulator_TEST_DEPENDS )
set(pedestrian_simulator_DOC_DEPENDS )
set(pedestrian_simulator_URL_WEBSITE "")
set(pedestrian_simulator_URL_BUGTRACKER "")
set(pedestrian_simulator_URL_REPOSITORY "")
set(pedestrian_simulator_DEPRECATED "")