//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the mpc_planner_rosnavigation package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __mpc_planner_rosnavigation__ROSNAVIGATIONCONFIG_H__
#define __mpc_planner_rosnavigation__ROSNAVIGATIONCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace mpc_planner_rosnavigation
{
  class rosnavigationConfigStatics;

  class rosnavigationConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(rosnavigationConfig &config, const rosnavigationConfig &max, const rosnavigationConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const rosnavigationConfig &config1, const rosnavigationConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, rosnavigationConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const rosnavigationConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, rosnavigationConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const rosnavigationConfig &config) const = 0;
      virtual void getValue(const rosnavigationConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T rosnavigationConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T rosnavigationConfig::* field;

      virtual void clamp(rosnavigationConfig &config, const rosnavigationConfig &max, const rosnavigationConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const rosnavigationConfig &config1, const rosnavigationConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, rosnavigationConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const rosnavigationConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, rosnavigationConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const rosnavigationConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const rosnavigationConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, rosnavigationConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, rosnavigationConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<rosnavigationConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(rosnavigationConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);


      }
    }

    

    bool state;
    std::string name;

    class WEIGHTS
{
  public:
    WEIGHTS()
    {
      state = true;
      name = "Weights";
    }

    void setParams(rosnavigationConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("acceleration"==(*_i)->name){acceleration = boost::any_cast<double>(val);}
        if("angular_velocity"==(*_i)->name){angular_velocity = boost::any_cast<double>(val);}
        if("slack"==(*_i)->name){slack = boost::any_cast<double>(val);}
        if("velocity"==(*_i)->name){velocity = boost::any_cast<double>(val);}
        if("reference_velocity"==(*_i)->name){reference_velocity = boost::any_cast<double>(val);}
        if("contour"==(*_i)->name){contour = boost::any_cast<double>(val);}
        if("lag"==(*_i)->name){lag = boost::any_cast<double>(val);}
        if("terminal_angle"==(*_i)->name){terminal_angle = boost::any_cast<double>(val);}
        if("terminal_contouring"==(*_i)->name){terminal_contouring = boost::any_cast<double>(val);}
      }
    }

    double acceleration;
double angular_velocity;
double slack;
double velocity;
double reference_velocity;
double contour;
double lag;
double terminal_angle;
double terminal_contouring;

    bool state;
    std::string name;

    
}weights;

}groups;



//#line 7 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      double acceleration;
//#line 8 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      double angular_velocity;
//#line 9 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      double slack;
//#line 10 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      double velocity;
//#line 11 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      double reference_velocity;
//#line 12 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      double contour;
//#line 13 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      double lag;
//#line 14 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      double terminal_angle;
//#line 15 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      double terminal_contouring;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("rosnavigationConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const rosnavigationConfig &__max__ = __getMax__();
      const rosnavigationConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const rosnavigationConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const rosnavigationConfig &__getDefault__();
    static const rosnavigationConfig &__getMax__();
    static const rosnavigationConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const rosnavigationConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void rosnavigationConfig::ParamDescription<std::string>::clamp(rosnavigationConfig &config, const rosnavigationConfig &max, const rosnavigationConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class rosnavigationConfigStatics
  {
    friend class rosnavigationConfig;

    rosnavigationConfigStatics()
    {
rosnavigationConfig::GroupDescription<rosnavigationConfig::DEFAULT, rosnavigationConfig> Default("Default", "", 0, 0, true, &rosnavigationConfig::groups);
rosnavigationConfig::GroupDescription<rosnavigationConfig::DEFAULT::WEIGHTS, rosnavigationConfig::DEFAULT> Weights("Weights", "Weights", 0, 1, true, &rosnavigationConfig::DEFAULT::weights);
//#line 7 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      __min__.acceleration = 0.0;
//#line 7 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      __max__.acceleration = 100.0;
//#line 7 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      __default__.acceleration = 1.0;
//#line 7 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      Weights.abstract_parameters.push_back(rosnavigationConfig::AbstractParamDescriptionConstPtr(new rosnavigationConfig::ParamDescription<double>("acceleration", "double", 1, "acceleration", "", &rosnavigationConfig::acceleration)));
//#line 7 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      __param_descriptions__.push_back(rosnavigationConfig::AbstractParamDescriptionConstPtr(new rosnavigationConfig::ParamDescription<double>("acceleration", "double", 1, "acceleration", "", &rosnavigationConfig::acceleration)));
//#line 8 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      __min__.angular_velocity = 0.0;
//#line 8 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      __max__.angular_velocity = 100.0;
//#line 8 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      __default__.angular_velocity = 1.0;
//#line 8 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      Weights.abstract_parameters.push_back(rosnavigationConfig::AbstractParamDescriptionConstPtr(new rosnavigationConfig::ParamDescription<double>("angular_velocity", "double", 1, "angular_velocity", "", &rosnavigationConfig::angular_velocity)));
//#line 8 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      __param_descriptions__.push_back(rosnavigationConfig::AbstractParamDescriptionConstPtr(new rosnavigationConfig::ParamDescription<double>("angular_velocity", "double", 1, "angular_velocity", "", &rosnavigationConfig::angular_velocity)));
//#line 9 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      __min__.slack = 0.0;
//#line 9 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      __max__.slack = 100.0;
//#line 9 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      __default__.slack = 1.0;
//#line 9 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      Weights.abstract_parameters.push_back(rosnavigationConfig::AbstractParamDescriptionConstPtr(new rosnavigationConfig::ParamDescription<double>("slack", "double", 1, "slack", "", &rosnavigationConfig::slack)));
//#line 9 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      __param_descriptions__.push_back(rosnavigationConfig::AbstractParamDescriptionConstPtr(new rosnavigationConfig::ParamDescription<double>("slack", "double", 1, "slack", "", &rosnavigationConfig::slack)));
//#line 10 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      __min__.velocity = 0.0;
//#line 10 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      __max__.velocity = 100.0;
//#line 10 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      __default__.velocity = 1.0;
//#line 10 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      Weights.abstract_parameters.push_back(rosnavigationConfig::AbstractParamDescriptionConstPtr(new rosnavigationConfig::ParamDescription<double>("velocity", "double", 1, "velocity", "", &rosnavigationConfig::velocity)));
//#line 10 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      __param_descriptions__.push_back(rosnavigationConfig::AbstractParamDescriptionConstPtr(new rosnavigationConfig::ParamDescription<double>("velocity", "double", 1, "velocity", "", &rosnavigationConfig::velocity)));
//#line 11 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      __min__.reference_velocity = 0.0;
//#line 11 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      __max__.reference_velocity = 100.0;
//#line 11 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      __default__.reference_velocity = 1.0;
//#line 11 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      Weights.abstract_parameters.push_back(rosnavigationConfig::AbstractParamDescriptionConstPtr(new rosnavigationConfig::ParamDescription<double>("reference_velocity", "double", 1, "reference_velocity", "", &rosnavigationConfig::reference_velocity)));
//#line 11 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      __param_descriptions__.push_back(rosnavigationConfig::AbstractParamDescriptionConstPtr(new rosnavigationConfig::ParamDescription<double>("reference_velocity", "double", 1, "reference_velocity", "", &rosnavigationConfig::reference_velocity)));
//#line 12 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      __min__.contour = 0.0;
//#line 12 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      __max__.contour = 100.0;
//#line 12 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      __default__.contour = 1.0;
//#line 12 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      Weights.abstract_parameters.push_back(rosnavigationConfig::AbstractParamDescriptionConstPtr(new rosnavigationConfig::ParamDescription<double>("contour", "double", 1, "contour", "", &rosnavigationConfig::contour)));
//#line 12 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      __param_descriptions__.push_back(rosnavigationConfig::AbstractParamDescriptionConstPtr(new rosnavigationConfig::ParamDescription<double>("contour", "double", 1, "contour", "", &rosnavigationConfig::contour)));
//#line 13 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      __min__.lag = 0.0;
//#line 13 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      __max__.lag = 100.0;
//#line 13 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      __default__.lag = 1.0;
//#line 13 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      Weights.abstract_parameters.push_back(rosnavigationConfig::AbstractParamDescriptionConstPtr(new rosnavigationConfig::ParamDescription<double>("lag", "double", 1, "lag", "", &rosnavigationConfig::lag)));
//#line 13 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      __param_descriptions__.push_back(rosnavigationConfig::AbstractParamDescriptionConstPtr(new rosnavigationConfig::ParamDescription<double>("lag", "double", 1, "lag", "", &rosnavigationConfig::lag)));
//#line 14 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      __min__.terminal_angle = 0.0;
//#line 14 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      __max__.terminal_angle = 100.0;
//#line 14 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      __default__.terminal_angle = 1.0;
//#line 14 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      Weights.abstract_parameters.push_back(rosnavigationConfig::AbstractParamDescriptionConstPtr(new rosnavigationConfig::ParamDescription<double>("terminal_angle", "double", 1, "terminal_angle", "", &rosnavigationConfig::terminal_angle)));
//#line 14 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      __param_descriptions__.push_back(rosnavigationConfig::AbstractParamDescriptionConstPtr(new rosnavigationConfig::ParamDescription<double>("terminal_angle", "double", 1, "terminal_angle", "", &rosnavigationConfig::terminal_angle)));
//#line 15 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      __min__.terminal_contouring = 0.0;
//#line 15 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      __max__.terminal_contouring = 100.0;
//#line 15 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      __default__.terminal_contouring = 1.0;
//#line 15 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      Weights.abstract_parameters.push_back(rosnavigationConfig::AbstractParamDescriptionConstPtr(new rosnavigationConfig::ParamDescription<double>("terminal_contouring", "double", 1, "terminal_contouring", "", &rosnavigationConfig::terminal_contouring)));
//#line 15 "/home/soon/workspace/src/mpc_planner/mpc_planner_rosnavigation/cfg/rosnavigation.cfg"
      __param_descriptions__.push_back(rosnavigationConfig::AbstractParamDescriptionConstPtr(new rosnavigationConfig::ParamDescription<double>("terminal_contouring", "double", 1, "terminal_contouring", "", &rosnavigationConfig::terminal_contouring)));
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Weights.convertParams();
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(rosnavigationConfig::AbstractGroupDescriptionConstPtr(new rosnavigationConfig::GroupDescription<rosnavigationConfig::DEFAULT::WEIGHTS, rosnavigationConfig::DEFAULT>(Weights)));
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(rosnavigationConfig::AbstractGroupDescriptionConstPtr(new rosnavigationConfig::GroupDescription<rosnavigationConfig::DEFAULT::WEIGHTS, rosnavigationConfig::DEFAULT>(Weights)));
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(rosnavigationConfig::AbstractGroupDescriptionConstPtr(new rosnavigationConfig::GroupDescription<rosnavigationConfig::DEFAULT, rosnavigationConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<rosnavigationConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<rosnavigationConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<rosnavigationConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    rosnavigationConfig __max__;
    rosnavigationConfig __min__;
    rosnavigationConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const rosnavigationConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static rosnavigationConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &rosnavigationConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const rosnavigationConfig &rosnavigationConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const rosnavigationConfig &rosnavigationConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const rosnavigationConfig &rosnavigationConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<rosnavigationConfig::AbstractParamDescriptionConstPtr> &rosnavigationConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<rosnavigationConfig::AbstractGroupDescriptionConstPtr> &rosnavigationConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const rosnavigationConfigStatics *rosnavigationConfig::__get_statics__()
  {
    const static rosnavigationConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = rosnavigationConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __ROSNAVIGATIONRECONFIGURATOR_H__
