set(_CATKIN_CURRENT_PACKAGE "mpc_planner_jackal")
set(mpc_planner_jackal_VERSION "0.0.0")
set(mpc_planner_jackal_MAINTAINER "Oscar de Groot <o.m.degroot@tudelft.nl>")
set(mpc_planner_jackal_PACKAGE_FORMAT "3")
set(mpc_planner_jackal_BUILD_DEPENDS "roscpp" "mpc_planner" "mpc_planner_solver" "mpc_planner_util" "mpc_planner_types" "mpc_planner_msgs" "ros_tools" "dynamic_reconfigure" "nav_msgs" "derived_object_msgs")
set(mpc_planner_jackal_BUILD_EXPORT_DEPENDS "roscpp" "mpc_planner" "mpc_planner_solver" "mpc_planner_util" "mpc_planner_types" "mpc_planner_msgs" "ros_tools" "dynamic_reconfigure" "nav_msgs" "derived_object_msgs")
set(mpc_planner_jackal_BUILDTOOL_DEPENDS "catkin")
set(mpc_planner_jackal_BUILDTOOL_EXPORT_DEPENDS )
set(mpc_planner_jackal_EXEC_DEPENDS "roadmap" "vicon_bridge" "vicon_util" "roscpp" "mpc_planner" "mpc_planner_solver" "mpc_planner_util" "mpc_planner_types" "mpc_planner_msgs" "ros_tools" "dynamic_reconfigure" "nav_msgs" "derived_object_msgs")
set(mpc_planner_jackal_RUN_DEPENDS "roadmap" "vicon_bridge" "vicon_util" "roscpp" "mpc_planner" "mpc_planner_solver" "mpc_planner_util" "mpc_planner_types" "mpc_planner_msgs" "ros_tools" "dynamic_reconfigure" "nav_msgs" "derived_object_msgs")
set(mpc_planner_jackal_TEST_DEPENDS )
set(mpc_planner_jackal_DOC_DEPENDS )
set(mpc_planner_jackal_URL_WEBSITE "")
set(mpc_planner_jackal_URL_BUGTRACKER "")
set(mpc_planner_jackal_URL_REPOSITORY "")
set(mpc_planner_jackal_DEPRECATED "")