set(_CATKIN_CURRENT_PACKAGE "roadmap")
set(roadmap_VERSION "0.0.0")
set(roadmap_MAINTAINER "r2c1 <r2c1@todo.todo>")
set(roadmap_PACKAGE_FORMAT "2")
set(roadmap_BUILD_DEPENDS "geometry_msgs" "roscpp" "std_msgs" "roslib" "asr_rapidxml" "roadmap_msgs" "ros_tools")
set(roadmap_BUILD_EXPORT_DEPENDS "geometry_msgs" "roscpp" "std_msgs" "roslib" "asr_rapidxml" "roadmap_msgs" "ros_tools")
set(roadmap_BUILDTOOL_DEPENDS "catkin")
set(roadmap_BUILDTOOL_EXPORT_DEPENDS )
set(roadmap_EXEC_DEPENDS "geometry_msgs" "roscpp" "std_msgs" "roslib" "asr_rapidxml" "roadmap_msgs" "ros_tools")
set(roadmap_RUN_DEPENDS "geometry_msgs" "roscpp" "std_msgs" "roslib" "asr_rapidxml" "roadmap_msgs" "ros_tools")
set(roadmap_TEST_DEPENDS )
set(roadmap_DOC_DEPENDS )
set(roadmap_URL_WEBSITE "")
set(roadmap_URL_BUGTRACKER "")
set(roadmap_URL_REPOSITORY "")
set(roadmap_DEPRECATED "")