set(_CATKIN_CURRENT_PACKAGE "mpc_planner_msgs")
set(mpc_planner_msgs_VERSION "0.0.0")
set(mpc_planner_msgs_MAINTAINER "Oscar de Groot <o.m.degroot@tudelft.nl>")
set(mpc_planner_msgs_PACKAGE_FORMAT "2")
set(mpc_planner_msgs_BUILD_DEPENDS "nav_msgs" "geometry_msgs" "std_msgs")
set(mpc_planner_msgs_BUILD_EXPORT_DEPENDS "nav_msgs" "geometry_msgs" "std_msgs")
set(mpc_planner_msgs_BUILDTOOL_DEPENDS "catkin")
set(mpc_planner_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(mpc_planner_msgs_EXEC_DEPENDS "nav_msgs" "geometry_msgs" "std_msgs")
set(mpc_planner_msgs_RUN_DEPENDS "nav_msgs" "geometry_msgs" "std_msgs")
set(mpc_planner_msgs_TEST_DEPENDS )
set(mpc_planner_msgs_DOC_DEPENDS )
set(mpc_planner_msgs_URL_WEBSITE "")
set(mpc_planner_msgs_URL_BUGTRACKER "")
set(mpc_planner_msgs_URL_REPOSITORY "")
set(mpc_planner_msgs_DEPRECATED "")