//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the guidance_planner package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __guidance_planner__GUIDANCEPLANNERRECONFIGURECONFIG_H__
#define __guidance_planner__GUIDANCEPLANNERRECONFIGURECONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace guidance_planner
{
  class GuidancePlannerReconfigureConfigStatics;

  class GuidancePlannerReconfigureConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(GuidancePlannerReconfigureConfig &config, const GuidancePlannerReconfigureConfig &max, const GuidancePlannerReconfigureConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const GuidancePlannerReconfigureConfig &config1, const GuidancePlannerReconfigureConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, GuidancePlannerReconfigureConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const GuidancePlannerReconfigureConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, GuidancePlannerReconfigureConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const GuidancePlannerReconfigureConfig &config) const = 0;
      virtual void getValue(const GuidancePlannerReconfigureConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T GuidancePlannerReconfigureConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T GuidancePlannerReconfigureConfig::* field;

      virtual void clamp(GuidancePlannerReconfigureConfig &config, const GuidancePlannerReconfigureConfig &max, const GuidancePlannerReconfigureConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const GuidancePlannerReconfigureConfig &config1, const GuidancePlannerReconfigureConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, GuidancePlannerReconfigureConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const GuidancePlannerReconfigureConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, GuidancePlannerReconfigureConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const GuidancePlannerReconfigureConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const GuidancePlannerReconfigureConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, GuidancePlannerReconfigureConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, GuidancePlannerReconfigureConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<GuidancePlannerReconfigureConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(GuidancePlannerReconfigureConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);


      }
    }

    

    bool state;
    std::string name;

    class ACTIONS
{
  public:
    ACTIONS()
    {
      state = true;
      name = "Actions";
    }

    void setParams(GuidancePlannerReconfigureConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("replan"==(*_i)->name){replan = boost::any_cast<bool>(val);}
        if("debug"==(*_i)->name){debug = boost::any_cast<bool>(val);}
        if("visualize_samples"==(*_i)->name){visualize_samples = boost::any_cast<bool>(val);}
      }
    }

    bool replan;
bool debug;
bool visualize_samples;

    bool state;
    std::string name;

    
}actions;

class PRM_SETTINGS
{
  public:
    PRM_SETTINGS()
    {
      state = true;
      name = "PRM_Settings";
    }

    void setParams(GuidancePlannerReconfigureConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("n_samples"==(*_i)->name){n_samples = boost::any_cast<int>(val);}
        if("n_paths"==(*_i)->name){n_paths = boost::any_cast<int>(val);}
        if("use_learning"==(*_i)->name){use_learning = boost::any_cast<bool>(val);}
      }
    }

    int n_samples;
int n_paths;
bool use_learning;

    bool state;
    std::string name;

    
}prm_settings;

}groups;



//#line 10 "/workspace/src/guidance_planner/cfg/GuidancePlannerReconfigure.cfg"
      bool replan;
//#line 11 "/workspace/src/guidance_planner/cfg/GuidancePlannerReconfigure.cfg"
      bool debug;
//#line 12 "/workspace/src/guidance_planner/cfg/GuidancePlannerReconfigure.cfg"
      bool visualize_samples;
//#line 15 "/workspace/src/guidance_planner/cfg/GuidancePlannerReconfigure.cfg"
      int n_samples;
//#line 16 "/workspace/src/guidance_planner/cfg/GuidancePlannerReconfigure.cfg"
      int n_paths;
//#line 18 "/workspace/src/guidance_planner/cfg/GuidancePlannerReconfigure.cfg"
      bool use_learning;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("GuidancePlannerReconfigureConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const GuidancePlannerReconfigureConfig &__max__ = __getMax__();
      const GuidancePlannerReconfigureConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const GuidancePlannerReconfigureConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const GuidancePlannerReconfigureConfig &__getDefault__();
    static const GuidancePlannerReconfigureConfig &__getMax__();
    static const GuidancePlannerReconfigureConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const GuidancePlannerReconfigureConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void GuidancePlannerReconfigureConfig::ParamDescription<std::string>::clamp(GuidancePlannerReconfigureConfig &config, const GuidancePlannerReconfigureConfig &max, const GuidancePlannerReconfigureConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class GuidancePlannerReconfigureConfigStatics
  {
    friend class GuidancePlannerReconfigureConfig;

    GuidancePlannerReconfigureConfigStatics()
    {
GuidancePlannerReconfigureConfig::GroupDescription<GuidancePlannerReconfigureConfig::DEFAULT, GuidancePlannerReconfigureConfig> Default("Default", "", 0, 0, true, &GuidancePlannerReconfigureConfig::groups);
GuidancePlannerReconfigureConfig::GroupDescription<GuidancePlannerReconfigureConfig::DEFAULT::ACTIONS, GuidancePlannerReconfigureConfig::DEFAULT> Actions("Actions", "Actions", 0, 1, true, &GuidancePlannerReconfigureConfig::DEFAULT::actions);
//#line 10 "/workspace/src/guidance_planner/cfg/GuidancePlannerReconfigure.cfg"
      __min__.replan = 0;
//#line 10 "/workspace/src/guidance_planner/cfg/GuidancePlannerReconfigure.cfg"
      __max__.replan = 1;
//#line 10 "/workspace/src/guidance_planner/cfg/GuidancePlannerReconfigure.cfg"
      __default__.replan = 0;
//#line 10 "/workspace/src/guidance_planner/cfg/GuidancePlannerReconfigure.cfg"
      Actions.abstract_parameters.push_back(GuidancePlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new GuidancePlannerReconfigureConfig::ParamDescription<bool>("replan", "bool", 0, "(Debug) Replan Homotopy", "", &GuidancePlannerReconfigureConfig::replan)));
//#line 10 "/workspace/src/guidance_planner/cfg/GuidancePlannerReconfigure.cfg"
      __param_descriptions__.push_back(GuidancePlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new GuidancePlannerReconfigureConfig::ParamDescription<bool>("replan", "bool", 0, "(Debug) Replan Homotopy", "", &GuidancePlannerReconfigureConfig::replan)));
//#line 11 "/workspace/src/guidance_planner/cfg/GuidancePlannerReconfigure.cfg"
      __min__.debug = 0;
//#line 11 "/workspace/src/guidance_planner/cfg/GuidancePlannerReconfigure.cfg"
      __max__.debug = 1;
//#line 11 "/workspace/src/guidance_planner/cfg/GuidancePlannerReconfigure.cfg"
      __default__.debug = 0;
//#line 11 "/workspace/src/guidance_planner/cfg/GuidancePlannerReconfigure.cfg"
      Actions.abstract_parameters.push_back(GuidancePlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new GuidancePlannerReconfigureConfig::ParamDescription<bool>("debug", "bool", 0, "Enable Debug Output", "", &GuidancePlannerReconfigureConfig::debug)));
//#line 11 "/workspace/src/guidance_planner/cfg/GuidancePlannerReconfigure.cfg"
      __param_descriptions__.push_back(GuidancePlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new GuidancePlannerReconfigureConfig::ParamDescription<bool>("debug", "bool", 0, "Enable Debug Output", "", &GuidancePlannerReconfigureConfig::debug)));
//#line 12 "/workspace/src/guidance_planner/cfg/GuidancePlannerReconfigure.cfg"
      __min__.visualize_samples = 0;
//#line 12 "/workspace/src/guidance_planner/cfg/GuidancePlannerReconfigure.cfg"
      __max__.visualize_samples = 1;
//#line 12 "/workspace/src/guidance_planner/cfg/GuidancePlannerReconfigure.cfg"
      __default__.visualize_samples = 0;
//#line 12 "/workspace/src/guidance_planner/cfg/GuidancePlannerReconfigure.cfg"
      Actions.abstract_parameters.push_back(GuidancePlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new GuidancePlannerReconfigureConfig::ParamDescription<bool>("visualize_samples", "bool", 0, "Visualize All Samples", "", &GuidancePlannerReconfigureConfig::visualize_samples)));
//#line 12 "/workspace/src/guidance_planner/cfg/GuidancePlannerReconfigure.cfg"
      __param_descriptions__.push_back(GuidancePlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new GuidancePlannerReconfigureConfig::ParamDescription<bool>("visualize_samples", "bool", 0, "Visualize All Samples", "", &GuidancePlannerReconfigureConfig::visualize_samples)));
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Actions.convertParams();
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(GuidancePlannerReconfigureConfig::AbstractGroupDescriptionConstPtr(new GuidancePlannerReconfigureConfig::GroupDescription<GuidancePlannerReconfigureConfig::DEFAULT::ACTIONS, GuidancePlannerReconfigureConfig::DEFAULT>(Actions)));
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(GuidancePlannerReconfigureConfig::AbstractGroupDescriptionConstPtr(new GuidancePlannerReconfigureConfig::GroupDescription<GuidancePlannerReconfigureConfig::DEFAULT::ACTIONS, GuidancePlannerReconfigureConfig::DEFAULT>(Actions)));
GuidancePlannerReconfigureConfig::GroupDescription<GuidancePlannerReconfigureConfig::DEFAULT::PRM_SETTINGS, GuidancePlannerReconfigureConfig::DEFAULT> PRM_Settings("PRM_Settings", "PRM Settings", 0, 2, true, &GuidancePlannerReconfigureConfig::DEFAULT::prm_settings);
//#line 15 "/workspace/src/guidance_planner/cfg/GuidancePlannerReconfigure.cfg"
      __min__.n_samples = 10;
//#line 15 "/workspace/src/guidance_planner/cfg/GuidancePlannerReconfigure.cfg"
      __max__.n_samples = 10000;
//#line 15 "/workspace/src/guidance_planner/cfg/GuidancePlannerReconfigure.cfg"
      __default__.n_samples = 30;
//#line 15 "/workspace/src/guidance_planner/cfg/GuidancePlannerReconfigure.cfg"
      PRM_Settings.abstract_parameters.push_back(GuidancePlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new GuidancePlannerReconfigureConfig::ParamDescription<int>("n_samples", "int", 1, "Number of Samples", "", &GuidancePlannerReconfigureConfig::n_samples)));
//#line 15 "/workspace/src/guidance_planner/cfg/GuidancePlannerReconfigure.cfg"
      __param_descriptions__.push_back(GuidancePlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new GuidancePlannerReconfigureConfig::ParamDescription<int>("n_samples", "int", 1, "Number of Samples", "", &GuidancePlannerReconfigureConfig::n_samples)));
//#line 16 "/workspace/src/guidance_planner/cfg/GuidancePlannerReconfigure.cfg"
      __min__.n_paths = 0;
//#line 16 "/workspace/src/guidance_planner/cfg/GuidancePlannerReconfigure.cfg"
      __max__.n_paths = 10;
//#line 16 "/workspace/src/guidance_planner/cfg/GuidancePlannerReconfigure.cfg"
      __default__.n_paths = 4;
//#line 16 "/workspace/src/guidance_planner/cfg/GuidancePlannerReconfigure.cfg"
      PRM_Settings.abstract_parameters.push_back(GuidancePlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new GuidancePlannerReconfigureConfig::ParamDescription<int>("n_paths", "int", 4, "Number of Paths", "", &GuidancePlannerReconfigureConfig::n_paths)));
//#line 16 "/workspace/src/guidance_planner/cfg/GuidancePlannerReconfigure.cfg"
      __param_descriptions__.push_back(GuidancePlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new GuidancePlannerReconfigureConfig::ParamDescription<int>("n_paths", "int", 4, "Number of Paths", "", &GuidancePlannerReconfigureConfig::n_paths)));
//#line 18 "/workspace/src/guidance_planner/cfg/GuidancePlannerReconfigure.cfg"
      __min__.use_learning = 0;
//#line 18 "/workspace/src/guidance_planner/cfg/GuidancePlannerReconfigure.cfg"
      __max__.use_learning = 1;
//#line 18 "/workspace/src/guidance_planner/cfg/GuidancePlannerReconfigure.cfg"
      __default__.use_learning = 0;
//#line 18 "/workspace/src/guidance_planner/cfg/GuidancePlannerReconfigure.cfg"
      PRM_Settings.abstract_parameters.push_back(GuidancePlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new GuidancePlannerReconfigureConfig::ParamDescription<bool>("use_learning", "bool", 0, "Use learning to choose topology", "", &GuidancePlannerReconfigureConfig::use_learning)));
//#line 18 "/workspace/src/guidance_planner/cfg/GuidancePlannerReconfigure.cfg"
      __param_descriptions__.push_back(GuidancePlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new GuidancePlannerReconfigureConfig::ParamDescription<bool>("use_learning", "bool", 0, "Use learning to choose topology", "", &GuidancePlannerReconfigureConfig::use_learning)));
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      PRM_Settings.convertParams();
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(GuidancePlannerReconfigureConfig::AbstractGroupDescriptionConstPtr(new GuidancePlannerReconfigureConfig::GroupDescription<GuidancePlannerReconfigureConfig::DEFAULT::PRM_SETTINGS, GuidancePlannerReconfigureConfig::DEFAULT>(PRM_Settings)));
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(GuidancePlannerReconfigureConfig::AbstractGroupDescriptionConstPtr(new GuidancePlannerReconfigureConfig::GroupDescription<GuidancePlannerReconfigureConfig::DEFAULT::PRM_SETTINGS, GuidancePlannerReconfigureConfig::DEFAULT>(PRM_Settings)));
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(GuidancePlannerReconfigureConfig::AbstractGroupDescriptionConstPtr(new GuidancePlannerReconfigureConfig::GroupDescription<GuidancePlannerReconfigureConfig::DEFAULT, GuidancePlannerReconfigureConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<GuidancePlannerReconfigureConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<GuidancePlannerReconfigureConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<GuidancePlannerReconfigureConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    GuidancePlannerReconfigureConfig __max__;
    GuidancePlannerReconfigureConfig __min__;
    GuidancePlannerReconfigureConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const GuidancePlannerReconfigureConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static GuidancePlannerReconfigureConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &GuidancePlannerReconfigureConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const GuidancePlannerReconfigureConfig &GuidancePlannerReconfigureConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const GuidancePlannerReconfigureConfig &GuidancePlannerReconfigureConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const GuidancePlannerReconfigureConfig &GuidancePlannerReconfigureConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<GuidancePlannerReconfigureConfig::AbstractParamDescriptionConstPtr> &GuidancePlannerReconfigureConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<GuidancePlannerReconfigureConfig::AbstractGroupDescriptionConstPtr> &GuidancePlannerReconfigureConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const GuidancePlannerReconfigureConfigStatics *GuidancePlannerReconfigureConfig::__get_statics__()
  {
    const static GuidancePlannerReconfigureConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = GuidancePlannerReconfigureConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __GUIDANCEPLANNERRECONFIGURERECONFIGURATOR_H__
