set(_CATKIN_CURRENT_PACKAGE "mpc_planner")
set(mpc_planner_VERSION "0.0.0")
set(mpc_planner_MAINTAINER "Oscar de Groot <o.m.degroot@tudelft.nl>")
set(mpc_planner_PACKAGE_FORMAT "3")
set(mpc_planner_BUILD_DEPENDS "mpc_planner_util" "mpc_planner_types" "mpc_planner_solver" "mpc_planner_modules" "ros_tools")
set(mpc_planner_BUILD_EXPORT_DEPENDS "mpc_planner_util" "mpc_planner_types" "mpc_planner_solver" "mpc_planner_modules" "ros_tools")
set(mpc_planner_BUILDTOOL_DEPENDS "catkin")
set(mpc_planner_BUILDTOOL_EXPORT_DEPENDS )
set(mpc_planner_EXEC_DEPENDS "mpc_planner_util" "mpc_planner_types" "mpc_planner_solver" "mpc_planner_modules" "ros_tools")
set(mpc_planner_RUN_DEPENDS "mpc_planner_util" "mpc_planner_types" "mpc_planner_solver" "mpc_planner_modules" "ros_tools")
set(mpc_planner_TEST_DEPENDS )
set(mpc_planner_DOC_DEPENDS )
set(mpc_planner_URL_WEBSITE "")
set(mpc_planner_URL_BUGTRACKER "")
set(mpc_planner_URL_REPOSITORY "")
set(mpc_planner_DEPRECATED "")