set(_CATKIN_CURRENT_PACKAGE "mpc_planner_util")
set(mpc_planner_util_VERSION "0.0.0")
set(mpc_planner_util_MAINTAINER "Oscar de Groot <o.m.degroot@tudelft.nl>")
set(mpc_planner_util_PACKAGE_FORMAT "3")
set(mpc_planner_util_BUILD_DEPENDS "roscpp" "mpc_planner_types" "ros_tools")
set(mpc_planner_util_BUILD_EXPORT_DEPENDS "roscpp" "mpc_planner_types" "ros_tools")
set(mpc_planner_util_BUILDTOOL_DEPENDS "catkin")
set(mpc_planner_util_BUILDTOOL_EXPORT_DEPENDS )
set(mpc_planner_util_EXEC_DEPENDS "roscpp" "mpc_planner_types" "ros_tools")
set(mpc_planner_util_RUN_DEPENDS "roscpp" "mpc_planner_types" "ros_tools")
set(mpc_planner_util_TEST_DEPENDS )
set(mpc_planner_util_DOC_DEPENDS )
set(mpc_planner_util_URL_WEBSITE "")
set(mpc_planner_util_URL_BUGTRACKER "")
set(mpc_planner_util_URL_REPOSITORY "")
set(mpc_planner_util_DEPRECATED "")