set(_CATKIN_CURRENT_PACKAGE "scenario_module")
set(scenario_module_VERSION "0.0.0")
set(scenario_module_MAINTAINER "r2c1 <r2c1@todo.todo>")
set(scenario_module_PACKAGE_FORMAT "2")
set(scenario_module_BUILD_DEPENDS "roscpp" "std_msgs" "ros_tools" "mpc_planner_types" "mpc_planner_msgs" "mpc_planner_util" "mpc_planner_solver")
set(scenario_module_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs" "ros_tools" "mpc_planner_types" "mpc_planner_msgs" "mpc_planner_util" "mpc_planner_solver")
set(scenario_module_BUILDTOOL_DEPENDS "catkin")
set(scenario_module_BUILDTOOL_EXPORT_DEPENDS )
set(scenario_module_EXEC_DEPENDS "roscpp" "std_msgs" "ros_tools" "mpc_planner_types" "mpc_planner_msgs" "mpc_planner_util" "mpc_planner_solver")
set(scenario_module_RUN_DEPENDS "roscpp" "std_msgs" "ros_tools" "mpc_planner_types" "mpc_planner_msgs" "mpc_planner_util" "mpc_planner_solver")
set(scenario_module_TEST_DEPENDS )
set(scenario_module_DOC_DEPENDS )
set(scenario_module_URL_WEBSITE "")
set(scenario_module_URL_BUGTRACKER "")
set(scenario_module_URL_REPOSITORY "")
set(scenario_module_DEPRECATED "")