set(_CATKIN_CURRENT_PACKAGE "ros_tools")
set(ros_tools_VERSION "1.0.0")
set(ros_tools_MAINTAINER "Oscar de Groot <o.m.degroot@tudelft.nl>")
set(ros_tools_PACKAGE_FORMAT "3")
set(ros_tools_BUILD_DEPENDS "roscpp" "roslib" "eigen" "geometry_msgs" "std_msgs" "visualization_msgs" "tf")
set(ros_tools_BUILD_EXPORT_DEPENDS "roscpp" "roslib" "eigen" "geometry_msgs" "std_msgs" "visualization_msgs" "tf")
set(ros_tools_BUILDTOOL_DEPENDS "catkin")
set(ros_tools_BUILDTOOL_EXPORT_DEPENDS )
set(ros_tools_EXEC_DEPENDS "roscpp" "roslib" "eigen" "geometry_msgs" "std_msgs" "visualization_msgs" "tf")
set(ros_tools_RUN_DEPENDS "roscpp" "roslib" "eigen" "geometry_msgs" "std_msgs" "visualization_msgs" "tf")
set(ros_tools_TEST_DEPENDS )
set(ros_tools_DOC_DEPENDS )
set(ros_tools_URL_WEBSITE "")
set(ros_tools_URL_BUGTRACKER "")
set(ros_tools_URL_REPOSITORY "")
set(ros_tools_DEPRECATED "")