set(_CATKIN_CURRENT_PACKAGE "asr_rapidxml")
set(asr_rapidxml_VERSION "1.0.0")
set(asr_rapidxml_MAINTAINER "Meißner Pascal <asr-ros@lists.kit.edu>")
set(asr_rapidxml_PACKAGE_FORMAT "1")
set(asr_rapidxml_BUILD_DEPENDS )
set(asr_rapidxml_BUILD_EXPORT_DEPENDS )
set(asr_rapidxml_BUILDTOOL_DEPENDS "catkin")
set(asr_rapidxml_BUILDTOOL_EXPORT_DEPENDS )
set(asr_rapidxml_EXEC_DEPENDS )
set(asr_rapidxml_RUN_DEPENDS )
set(asr_rapidxml_TEST_DEPENDS )
set(asr_rapidxml_DOC_DEPENDS )
set(asr_rapidxml_URL_WEBSITE "http://ros.org/wiki/asr_rapidxml")
set(asr_rapidxml_URL_BUGTRACKER "")
set(asr_rapidxml_URL_REPOSITORY "")
set(asr_rapidxml_DEPRECATED "")