set(_CATKIN_CURRENT_PACKAGE "mobile_robot_state_publisher")
set(mobile_robot_state_publisher_VERSION "0.0.0")
set(mobile_robot_state_publisher_MAINTAINER "bdebrito <bdebrito@tudelf.nl>")
set(mobile_robot_state_publisher_PACKAGE_FORMAT "2")
set(mobile_robot_state_publisher_BUILD_DEPENDS "geometry_msgs" "nav_msgs" "roscpp" "rospy" "std_msgs" "tf" "tf2" "tf2_ros" "tf2_geometry_msgs")
set(mobile_robot_state_publisher_BUILD_EXPORT_DEPENDS )
set(mobile_robot_state_publisher_BUILDTOOL_DEPENDS "catkin")
set(mobile_robot_state_publisher_BUILDTOOL_EXPORT_DEPENDS )
set(mobile_robot_state_publisher_EXEC_DEPENDS "geometry_msgs" "nav_msgs" "roscpp" "rospy" "std_msgs" "tf" "tf2" "tf2_ros" "tf2_geometry_msgs")
set(mobile_robot_state_publisher_RUN_DEPENDS "geometry_msgs" "nav_msgs" "roscpp" "rospy" "std_msgs" "tf" "tf2" "tf2_ros" "tf2_geometry_msgs")
set(mobile_robot_state_publisher_TEST_DEPENDS )
set(mobile_robot_state_publisher_DOC_DEPENDS )
set(mobile_robot_state_publisher_URL_WEBSITE "")
set(mobile_robot_state_publisher_URL_BUGTRACKER "")
set(mobile_robot_state_publisher_URL_REPOSITORY "")
set(mobile_robot_state_publisher_DEPRECATED "")